# The overall format is standard TOML format, v0.5.0.
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[31,)" #mandatory
issueTrackerURL="https://github.com/Sinhika/OnlySilver/issues"
logoFile=""
license="LGPL 3+"

[[mods]]
modId="onlysilver"
version="${version}"
displayName="Zot's Only Silver"
updateJSONURL="https://raw.githubusercontent.com/Sinhika/OnlySilver/1.15/update.json"
displayURL="http://minecraft.curseforge.com/projects/zots-only-silver"
credits="Zot201 (original mod), Sinhika (fork, maintenance, ports)."
authors="Zot201, Sinhika"
description='''
A single ore mod, featuring silver ore: silver tools, armor, enchantments and other things made from it. 

Additional Credits: 
'''

[[dependencies.onlysilver]]
    modId="simpleores"
    mandatory=true
    versionRange="[1.15.2-2.1.8.0,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.onlysilver]] #optional
    modId="forge"
    mandatory=true
    versionRange="[31.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.onlysilver]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,]"
    ordering="NONE"
    side="BOTH"