# The overall format is standard TOML format, v0.5.0.
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[35,)" #mandatory
issueTrackerURL="https://github.com/Sinhika/OnlySilver/issues"
license="LGPL 3+"

[[mods]]
modId="onlysilver"
version="${version}"
displayName="Zot's Only Silver"
updateJSONURL="https://raw.githubusercontent.com/Sinhika/OnlySilver/1.16.4/update.json"
displayURL="http://minecraft.curseforge.com/projects/zots-only-silver"
credits="Zot201 (original mod), Sinhika (fork, maintenance, ports)."
authors="Zot201, Sinhika"
description='''
A Lost Ore from SimpleOres: silver! Features silver tools, armor, enchantments and other things made from it. 

Additional Credits: 
'''

[[dependencies.onlysilver]]
    modId="forge"
    mandatory=true
    versionRange="[35.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.onlysilver]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.onlysilver]]
    modId="simplecorelib"
    mandatory=true
    versionRange="[1.16.4-2.0.4.3,1.16.4-2.0.5.0)"
    ordering="NONE"
    side="BOTH"

