# The overall format is standard TOML format, v0.5.0.
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[36,)" #mandatory
issueTrackerURL="https://github.com/Sinhika/OnlySilver/issues"
license="LGPL 3+"

[[mods]]
modId="onlysilver"
version="${file.jarVersion}"
displayName="Zot's Only Silver"
updateJSONURL="https://raw.githubusercontent.com/Sinhika/OnlySilver/1.16/update.json"
displayURL="http://minecraft.curseforge.com/projects/zots-only-silver"
credits="Zot201 (original mod), Sinhika (fork, maintenance, ports)."
authors="Zot201, Sinhika"
description='''
A Lost Ore from SimpleOres: silver! Features silver tools, armor, enchantments and other things made from it. 

Additional Credits: 
'''

[[dependencies.onlysilver]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.onlysilver]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.onlysilver]]
    modId="simplecorelib"
    mandatory=true
    versionRange="[1.16.5-2.0.7.5, 1.16.5-2.0.8.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies.onlysilver]]
        modId="silents_mechanisms"
        mandatory=false
        versionRange="[1.16.3-0.8.9,)"
        ordering="BEFORE"
        side="BOTH"
        
[[dependencies.onlysilver]]
        modId="silentgear"
        mandatory=false
        versionRange="[1.16.3-2.5.2,)"
        ordering="BEFORE"
        side="BOTH"

